#the following script was generated by chatgpt to speed up testing
from extract.shared.http import get_soup
from extract.shared.links import normalize_links, extract_product_url
from extract.shared.html_extractors import extract_json_block, extract_materials
from extract.sites.aym.parser import build_product_dict
from extract.sites.aym.config import CONFIG




base_url=CONFIG["base_url"]
category_locators=CONFIG["category_locators"]
product_locator=CONFIG["product_locator"]
materials_locator=CONFIG["materials_locator"]


print("STEP 1: CATEGORY LINKS")
category_links=normalize_links(base_url, category_locators)
print(category_links)


print("\nSTEP 2: PRODUCT LINKS (first category only)")

# pick first category
category_url=category_links[0]

# infer category name from URL (same logic as scraper)
if "tops" in category_url:
    category_name="Tops"
elif "bottoms" in category_url:
    category_name="Bottoms"
elif "dresses" in category_url:
    category_name="Dresses"
else:
    category_name="Unknown"

soup=get_soup(category_url)

raw_urls=extract_product_url(soup, product_locator)
product_links=normalize_links(base_url, raw_urls)

print(product_links[:5])


print("\nSTEP 3: SINGLE PRODUCT TEST")

test_link=product_links[0]
print("Testing:", test_link)

product_soup=get_soup(test_link)

json_data=extract_json_block(product_soup)
materials=extract_materials(product_soup, materials_locator)

print("JSON:", json_data is not None)
print("Materials:", materials)


print("\nSTEP 4: FINAL PRODUCT OBJECT")

product=build_product_dict(json_data, materials, category_name)
print(product)