category_dictionary={

    # Tops
    "t-shirt": "tops",
    "t-shirts": "tops",
    "tee": "tops",
    "tees": "tops",
    "tank top": "tops",
    "tank tops": "tops",
    "vest": "tops",
    "vests": "tops",
    "top": "tops",
    "tops": "tops",
    "shirt": "tops",
    "shirts": "tops",
    "blouse": "tops",
    "blouses": "tops",
    "bodysuit": "tops",
    "bodysuits": "tops",
    "crop top": "tops",
    "crop tops": "tops",
    "cape":"tops",
    "capes":"tops",
    "clothing tops":"tops",
    "clothing":"tops",
    # Bottoms
    "trouser": "bottoms",
    "trousers": "bottoms",
    "pant": "bottoms",
    "pants": "bottoms",
    "jean": "bottoms",
    "jeans": "bottoms",
    "short": "bottoms",
    "shorts": "bottoms",
    "skirt": "bottoms",
    "skirts": "bottoms",
    "skort": "bottoms",
    "skorts": "bottoms",
    "culottes": "bottoms",
    "legging": "bottoms",
    "leggings": "bottoms",

    # Dresses
    "dress": "dresses",
    "dresses": "dresses",
    "jumpsuit": "dresses",
    "jumpsuits": "dresses",
    "co-ord": "dresses",
    "co-ords": "dresses",
    "romper": "dresses",
    "rompers": "dresses",
    "overall": "dresses",
    "overalls": "dresses",
}